config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about', as: 'about'
  
  get 'imh' => 'pages#imh', as: 'imh'
  
  get 'patientdb' => 'patients#patientdb', as: 'patientdb'

  get 'index' => 'welcome#index'
   
  get 'patientspage' => 'patients#patientspage', as: 'patientspage'
  
  get 'updated' => 'patients#updated', as: 'updated'
  
  get 'search' => 'patients#index', as: 'search'
  
  get 'welcome/index'
  
  get 'newpatient' => 'patients#newpatient'
  
  resources :patients do
	resources :requests
  end
	
  
  root 'welcome#index', as: 'home'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/newpatient.rb
class Newpatient < ApplicationRecord
end

app/models/patient.rb
class Patient < ApplicationRecord
	has_many :requests, dependent: :destroy  # Allows for destroy of patient with note FK conflictions

	def self.search(search)
		if search
			where(["firstname || secondname || illness || address ILIKE ?","%#{search}%"])  #	ILIKE to make it case insensitive		
		else		#multiple arguments for the search
			all
		end
	end
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :patient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def application 
  
  @patients = Patient.search(params[:search])
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@aboutcontent1 = 'The I.M.H. (Irish Medical Hub) is an organization made up of 330 individuals, 40 of these are professionals in their fields with
		a combined years of experience surpassing 800. The professions these people hold cover the entire range of medical interest be it mental health
		well-being or emergency medical training, every field is covered. This grouping is the head board of the I.M.H. and they consult with one another 
		regaurding any chenges or developments that should be applied to the medical sector, these are agreed upon, polished and then presented to the 
		Department of Health. Any propositions will have a marking of importance ranging from 1 - 10 and be accompanied by a "Expected result if not 
		followed" section detailing the I.M.H.s expectated consequence if the guidelines are not followed.';
		
		@aboutcontent2 = 'The remainder of the organisation is made up of small teams oriented towards a specific field, these are the professionals with
		their fingers on the pulse of healthcare industry, doctors, physicians, behavioural therapists, phamacists are but a few of the titles held by team
		members. These teams meet with the head board and discuss findings of medical interests, current standards upcoming events/conferences of interests,
		research and development, medical data etc. Through this process understandings and ideas are developed in order to create a feasible readplan for 
		the future of Irish medical and healthcare system.';		
		
	end
	
	def imh
		@title = 'What is the I.M.H.';
		@content = 'The I.M.H. (Irish Medical Hub) was established as part of a new developmental strategy initiated by the H.S.E. (Health Service
		Executive) and the Irish government. This platform is the first step in the reshaping and redaploying of the Irish medical services, The 
		purpose of this softwares is to cantralise medical information on the countries populous. only medical professionel have access to the 
		information';
		
		@content2 = 'The Medical field in Ireland has been booming in R & D while
		the standards of the services directly availabale to the Irish people has
		seen some decline. Following an overhaul of the HSEs financial management 
		and spending patterns; futher expenses have been allocated to development 
		of this internal software and its evolution in the future.';
	
	end
	
	
	
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	http_basic_authenticate_with name: "Conor", password: "Conlon", accept: [:about]
	

	def patientspage								# PatientPage view elements
		@title = 'Patients';
		@patientspagecontent1 = 'Patients and the execution of service are the number one focus of the I.M.H. With good service and high quality 
		data analysis we hope to create a healthier future for the people of Ireland. The patients section allows medical practitioners to update
		data about patients, create new ones, query the database to find information on a patient or remove corrupt data on a patient. You will 
		need to be signed in if you wish to use any of these features';		
			
	end
	
	def index
		@title = 'Search Results'
		@patients = Patient.search(params[:search])
	end
	
	
	def patientdb									# PatientDB view elements
		@title = 'Patients Database';
		@patientdbcontent1 = 'The patients database displays patient data and also allows for searching. It is intended for use by medical 
		professional only.';
		@patients = Patient.all						
	end
	
	def newpatient									# New view elements
		@title = 'Please add info about the new Patient';
	end
	
	def show										# Show view elements
		@title = 'Patient details';
		@patient = Patient.find(params[:id])		# send the user to a page displaying the new patient added		
	end
	
	def create										# Method to create patient
		@patient = Patient.new(patient_params)  	
		#@patient.save
		if(@patient.save)
			redirect_to @patient
		else
			render 'new'
		end
#render 'patientspage'
		#redirect_to @patients_path
		#return
	end
		
	
	def edit										# Edit view elements
		@title = 'Update Patient Data'
		@content = 'Welcome to the patients edit page, please ensure any changes made 
		to patients details before saving.'
		@patient = Patient.find(params[:id])
	end
	
	def update										#method to update patient
		@patient = Patient.find(params[:id])
		if(@patient.update(patient_params))
			
			redirect_to @patient
		else
			render 'updated'
		end
	end
													#method to destroy patient
	def destroy
		@patient = Patient.find(params[:id])
		@patient.destroy
		
		render 'patientspage'		
		
	end
													
	def updated
		@patient = Patient.find(params[:id])
		@title = 'Patient Data Updated'
	
	end
	
	
	private def patient_params						# Patient Params
		params.require(:patient).permit(:firstname, :secondname, :dateofbirth, :address, :phonenumber, :illness, :relevantmedicalinfo, :nextofkinfirstname, :nextofkinsecondname, :nextofkincontactnumber, :nextofkinaddress)
	
	end
	
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	http_basic_authenticate_with name: "Conor", password: "Conlon"

	def create
		@patient = Patient.find(params[:patient_id])
		@request = @patient.requests.create(request_params)
		redirect_to patient_path(@patient)
	
	end
	
	private def request_params 
		params.require(:request).permit(:notes, :request)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	@title = 'Welcome to the I.M.H. Patient Management System';
	@welcomecontent1 = 'This is the Health Service Executives software for use by professionals in the medical health industry in
	the	Republic of Irelands. Please login to begin using the service, once logged in navigate the the patients section to access 
	the main features of the service. Basic information about this service are viewable
	on this site but any further functionality requires login credentials' 

	@welcomecontent2 = 'The functinality availabale to registered users includes - ' 	
	
	@welcomecontent3 ='Adding patients to the database'
	@welcomecontent4 ='editing a patients details or deleting a patient
						from the system altogether'
	@welcomecontent5 ='Submit requests regarding a patient'
	@welcomecontent6 ='Search the database of patients'
	
	end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shcpms</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>	
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="http://code.jquery.com/jquery-latest.min.js"></script> <script src="js/bootstrap.min.js"></script>

	<%= favicon_link_tag 'tablogo.png' %>
	
  </head>
		<!-- This is the base html file that the others estend from -->
  <body>
	<div>
	<%= image_tag "banner.png", alt: "banner_pic", class: "img-responsive", style:"width: 100%; height: 150px"%>
	</div>


	
<nav class="navbar navbar-inverse">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
	
		<div class="collapse navbar-collapse" id="myNavbar"> 
			<ul class="nav navbar-nav">
			<li><%= link_to "I.M.H.", imh_path %></li>
			  <li><%= link_to "Home", home_path %></li>
			  <li><%= link_to "About", about_path %></li>
			  <li><%= link_to "Patients", patientspage_path %></li>
			  
			  <li>
				<%= form_tag patients_path, :method => 'get' do  %>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag 'Search' %>
				<% end %>
				
			</li>
			<li><p style="color:white; padding-top:15px; padding-left:5px">
				Search based on first name, second name, address or illness
			</li>
			  
			</ul>
			
			
			
		</div>
	</div>
</nav>
	
 
    <%= yield %>
		
  </body>
</html>

app/views/pages/about.html.erb
<div class ="container" id = "main">
	<div class = "row">	
		<div class="col-lg-12">
			<div id = "aboutcontent">
				<h1><%= @title %></h1>
					<p1>
						<div id = "bord">
							<%= image_tag "board.png", alt: "bord_pic", class: "img-responsive"%>
						</div>
						<%= @aboutcontent1%>
					</p1>
				
					<p>
					</p>
					
					<p1>
						<%= @aboutcontent2%>
					</p1>
					
					<p>
					</p>
					
					<p1>
						<%= @aboutcontent3%>
					</p1>
				

			</div>
		</div>
	</div>
</div>

app/views/pages/imh.html.erb
<div class ="container" id = "main">
	<div class = "row">	
		<div class="col-lg-12">

			<h1><%= @title %></h1>
				<div id = "imhcontent">
					<p1>
						<div id = "cent">
							<%= image_tag "centralised.png", alt: "cen_pic", class: "img-responsive"%>
						</div>
						<%= @content %>
						<p></p>
						<%= @content2 %>
					</p1>
				</div>

		</div>
	</div>
</div>

app/views/patients/edit.html.erb
<div class ="container" id = "main">

	<div class = "row">
	
		<div class="col-lg-12">
			
			<h1><%= @title %></h1>
			
			<div id = "editcontents">
				<p1><%= @content %></p1>
				</br>
			</div>
			
			<div id = dbinner>
			</br>
			<div id = "editbackbtn">
			
				<%= link_to "Return to Patient Details", patient_path(@patient)%></li>
			
			</div>
			
			
			<div id = "npform">
								
								<!--required field and date picker added-->
								
				<%= form_for :patient, url: patient_path(@patient), method: :patch do |f| %>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :first_name %><span id = "field">
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :firstname, :required => 'required' %>
						</div>				
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :second_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :secondname, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :date_of_birth %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :dateofbirth, "data-provide" => 'datepicker', :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :address %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :address, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :phone_number %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :phonenumber, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :illness %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :illness, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :relevant_medical_information %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :relevantmedicalinfo, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_first_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinfirstname, :required => 'required' %>
						</div>	
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_second_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinsecondname, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_contact_number %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkincontactnumber, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_address %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinaddress, :required => 'required' %>
						</div>
					</p>
		
					
					
						<p>
							<div id = "npfb">		
							<%= f.submit :'Update Patient Details',
										data: {:confirm => 'Are you sure?'}%>
							</div>	
						</p>
						
						
					
				</div>
				</div>	
			<% end %>
		</div>
	</div>
</div>

app/views/patients/index.html.erb
<div class ="container" id = "main">
	<div class = "row">
	
		<!-- This page is displayed to the user when they submit a search -->
	
		<div class="col-lg-12">
			<h1><%= @title %></h1>
				<div id ="pdbcontent">
					<p><%= @patientdbcontent1%></p>
					
				</div>
				<!--
					<%= form_tag patients_path, :method => 'get' do  %>
						<%= text_field_tag :search, params[:search] %>
						<%= submit_tag 'Search' %>
					<% end %>	
				-->
				
			<div class = "searchtable">
				<table>
					<thead>
						<tr>
							<th>Patient ID</th>
							<th>First Name</th>
							<th>Second Name</th>
							<th>Date of Birth</th>
							<th>Address</th>
							<th>Contact_Number</th>
							<th colspan="6"></th>
						</tr>
					</thead>
				
				<tbody>
						<% @patients.each do |patient| %>
						<p><%= link_to 'View Details', patient_path(patient) %></p>
							<tr>
								<td><%= patient.id %></td><p>
								<td><%= patient.firstname %></td>
								<td><%= patient.secondname %></td>
								<td><%= patient.dateofbirth %></td>
								<td><%= patient.address %></td>
								<td><%= patient.phonenumber %></td>
							</tr>
							
						<% end %>
				
					</tbody>
				</table>
				
				</br>
				
				<table>
					<thead>
						<tr>
							<th>Illness</th>
							<th>Relevant Medical Information</th>
							<th>Next of Kin First Name</th>
							<th>Next of Kin Second Name</th>
							<th>Next of Kin Contact Number</th>
							<th>Next of Kin Address</th>
							<th>Date entered into System</th>
							<th colspan="7"></th>
						</tr>
					</thead>
				
				<tbody>
						<% @patients.each do |patient| %>
							<tr>
								<td><%= patient.illness %></td>
								<td><%= patient.relevantmedicalinfo %></td>
								<td><%= patient.nextofkinfirstname %></td>
								<td><%= patient.nextofkinsecondname %></td>
								<td><%= patient.nextofkincontactnumber %></td>
								<td><%= patient.nextofkinaddress %></td>
								<td><%= patient.created_at %></td>
								<td colspan="6"></td>
								
							</tr>
							
						<% end %>
				
					</tbody>
				</table>
				</br>
				
			</div>
				
		</div>
	</div>
</div>

app/views/patients/newpatient.html.erb
<div class ="container" id = "main">

	<div class = "row">
	
		<div class="col-lg-12">
			
			<h1><%= @title %></h1>
			<p1><%= @content %></p1>

			<div id = "npform">
																	<!--required field and date picker added-->
				<%= form_for :patient, url: patients_path do |f| %>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :first_name %><span id = "field">
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :firstname, :required => 'required' %>
						</div>				
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :second_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :secondname, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :date_of_birth %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :dateofbirth, "data-provide" => 'datepicker', :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :address %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :address, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :phone_number %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :phonenumber, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :illness %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :illness, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :relevant_medical_information %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :relevantmedicalinfo, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_first_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinfirstname, :required => 'required' %>
						</div>	
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_second_name %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinsecondname, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_contact_number %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkincontactnumber, :required => 'required' %>
						</div>
					</p>
					<p>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.label :next_of_kin_address %>
						</div>
						<div class="col-lg-6 col-md-6 col-sm-6">
							<%= f.text_field :nextofkinaddress, :required => 'required' %>
						</div>
					</p>
		
					
					
						<p>
							<div id = "npfb">		
								<%= f.submit :'Submit New Patient' %>
							</div>	
						</p>
					
				</div>
					
			<% end %>
		</div>
	</div>
</div>

app/views/patients/patientdb.html.erb
<div class ="container" id = "main">
	<div class = "row">
		<div class="col-lg-12">
			<h1><%= @title %></h1>
				<div id ="pdbcontent">
					<p><%= @patientdbcontent1%></p>
					
				</div>
					<div id = "pdblist">
						<% @patients.each do |patient|%>
						</br>
						<%= link_to "View Entry", patient_path(patient) %>
							<div id = "dbinner">
								<h3>Patient ID: <%= patient.id %></h3>
								<h3>Patient First Name: <%= patient.firstname %></h3>
								<h3>Patient Second Name: <%= patient.secondname %></h3>
								<h3>Patient Date of Birth: <%= patient.dateofbirth %></h3>
								<h3>Patient Address: <%= patient.address %></h3>
								<h3>Phone Number: <%= patient.phonenumber %></h3>
								<h3>Illness: <%= patient.illness %></h3>
								<h3>Relevant Medical Information: <%= patient.relevantmedicalinfo %></h3>
								<h3>Next of Kin First Name: <%= patient.nextofkinfirstname %></h3>
								<h3>Next of Kin second Name: <%= patient.nextofkinsecondname %></h3>
								<h3>Next of Kin Contact Number: <%= patient.nextofkincontactnumber %></h3>
								<h3>Next of Kin Address: <%= patient.nextofkinaddress %></h3>
							</div>
						<% end %>
					<div>
		</div>
	</div>
</div>

app/views/patients/patientspage.html.erb
<div class ="container" id = "main">

	<div class = "row">
	
		<div class="col-lg-12">
			
			<h1><%= @title %></h1>
			
					
					<div id = "pplinks">
						<div id = "links">
							<%= link_to "Add New Patient", newpatient_path %></li>
							<%= link_to "View Patient Database", patientdb_path %></li>
						</div>
					</div>
				
			<p1>
				
				<p1>
					<div id = "ppimg">
						<%= image_tag "patients.png", alt: "pat_pic", class: "img-responsive"%>
					</div>
					
				</p1>
				<div id = "ppcontent1">
					<%= @patientspagecontent1 %>
				</div>
				
				
			</p1>
			
				
		</div>
	</div>
</div>

app/views/patients/show.html.erb
<div class ="container" id = "main">
	<div class = "row">
	
		<!--This page is displayed to the user when the create or click on view dateils -->
		
		<div class="col-lg-12">
			
			<div id = "pdblistshow">
			
				</p>
				
				<%= button_to "Delete", patient_path(@patient),
								method: :delete, data: {confirm: "Are you sure?"},	
								data: {confirm: 'Are you sure'}%>
				
				<%= link_to "Back to Database", patientdb_path %></li>
				
				<%= link_to "Edit", edit_patient_path(@patient)%></li>
				
				
				
				</br>
				</br>					
					
			</div>
					
			
			
			<div id ="shownewp">	
				<div id ="dbinner">
					<h1><%= @title %></h1>
					<h3>Patient ID: <%= @patient.id %></h3>
					<h3>First Name: <%= @patient.firstname %></h3>
					<h3>Second Name: <%= @patient.secondname %></h3>
					<h3>Date of Birth: <%= @patient.dateofbirth %></h3>
					<h3>Address: <%= @patient.address %></h3>
					<h3>Phone Number: <%= @patient.phonenumber %></h3>
					<h3>Illness: <%= @patient.illness %></h3>
					<h3>Relevant Medical Information: <%= @patient.relevantmedicalinfo %></h3>
					<h3>Next of Kin First Name: <%= @patient.nextofkinfirstname %></h3>
					<h3>Next of Kin Second Name: <%= @patient.nextofkinsecondname %></h3>
					<h3>Next of Kin Contact Number: <%= @patient.nextofkincontactnumber %></h3>
					<h3>Next of Kin Address: <%= @patient.nextofkinaddress %></h3>
					<h3>Created: <%= @patient.created_at.strftime("%B %d %Y, %l:%M%P") %></h3>
				
				</div>
			</div>
			
			<div id = "nr">
				<h1>Notes and Requests</h1>
				<% @patient.requests.each do |request| %>
					<div class ="well">
												
							<p>Note: <%= request.notes %> </p>
							<p>Request: <%= request.request %></p>	
							
					</div>
				<% end %>
				
				<h1>Add a Note and/or Request</h1>
				<%= form_for([@patient,@patient.requests.build]) do |f|%>
					
					<div class="col-lg-6 col-md-6 col-sm-6">
						<p>
							<%= f.label :Note %>:
							<%= f.text_field :notes %>
						</p>
					</div>

					<div class="col-lg-6 col-md-6 col-sm-6">
					
						<p>
							<%= f.label :Request %>:
							<%= f.text_field :request %>
						</p>
						
					</div>
					
					<p id = "notebtn">
						<%= f.submit :'Submit Note and Request' %>
					</p>				
										
				<% end %>
			</div>
			
		</div>
	</div>
</div>

app/views/patients/updated.html.erb
<div class ="container" id = "main">
	<div class = "row">
		
		<div class="col-lg-12">
			
			<div id = "pdblistshow">
				</p>
				<%= link_to "Back to Database", patientdb_path %></li>
				</p>
				<%= link_to "Edit", edit_patient_path(@patient)%></li>
			</div>
					
			
			
			<div id ="shownewp">		
				<h1><%= @title %></h1>
				<h3>Patient ID: <%= @patient.id %></h3>
				<h3>First Name: <%= @patient.firstname %></h3>
				<h3>Second Name: <%= @patient.secondname %></h3>
				<h3>Date of Birth: <%= @patient.dateofbirth %></h3>
				<h3>Address: <%= @patient.address %></h3>
				<h3>Phone Number: <%= @patient.phonenumber %></h3>
				<h3>Illness: <%= @patient.illness %></h3>
				<h3>Relevant Medical Information: <%= @patient.relevantmedicalinfo %></h3>
				<h3>Next of Kin First Name: <%= @patient.nextofkinfirstname %></h3>
				<h3>Next of Kin Second Name: <%= @patient.nextofkinsecondname %></h3>
				<h3>Next of Kin Contact Number: <%= @patient.nextofkincontactnumber %></h3>
				<h3>Next of Kin Address: <%= @patient.nextofkinaddress %></h3>
				<h3>Created: <%= @patient.created_at.strftime("%B %d %Y, %l:%M%P") %></h3>
				
				
			<div id ="shownewp">
			
			
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div class ="container" id = "main">
	<div class = "row">
		<div class="col-lg-12">
			
			<h1><%= @title %></h1>
			<div id = "wcontent1">
				
				<p1>
					<%= @welcomecontent1 %>
					<p></p>
					
					<%= @welcomecontent2 %>
				</p1>
				<ul>
					<li style="background:#bdffbd;">
						<%= @welcomecontent3 %>
					</li>
					<li>
						<%= @welcomecontent4 %>
					</li>
					<li style="background:#bdffbd;">
						<%= @welcomecontent5 %>
					</li>
					<li>
						<%= @welcomecontent6 %>
					</li>
					
				</ul>
				
			</div>
			
		</div>
	</div>	
</div>